"use client";

import { jsPDF } from "jspdf";

type ReportStudy = {
  studyUid: string;
  patientName?: string | null;
  title?: string | null;
  studyDate?: string | null;
  description?: string | null;
  status?: string;
  series: {
    modality?: string | null;
    instanceCount: number;
    equipment?: {
      manufacturer?: string | null;
      manufacturerModelName?: string | null;
      stationName?: string | null;
    };
  }[];
};

export async function generatePdfReport(
  study: ReportStudy,
  canvas: HTMLCanvasElement,
  plan?: string,
) {
  const doc = new jsPDF("portrait", "mm", "a4");
  const pageW = 210;
  const margin = 20;
  const contentW = pageW - margin * 2;

  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(52, 211, 153);
  doc.text("CoreVita", margin, 25);

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text(`Report generated ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}`, margin, 32);

  // Separator
  doc.setDrawColor(52, 211, 153, 0.3);
  doc.setLineWidth(0.3);
  doc.line(margin, 36, pageW - margin, 36);

  // Study info
  let y = 46;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text(study.title || study.patientName || "Unknown Study", margin, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);

  const infoLines: string[] = [];
  if (study.patientName) infoLines.push(`Patient: ${study.patientName}`);
  if (study.studyDate) infoLines.push(`Date: ${study.studyDate}`);
  if (study.status) infoLines.push(`Status: ${study.status}`);
  if (study.description) infoLines.push(`Description: ${study.description}`);

  if (infoLines.length > 0) {
    doc.text(infoLines.join("   |   "), margin, y);
    y += 10;
  }

  // Series breakdown
  if (study.series.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(52, 211, 153);
    doc.text("Series", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    for (let i = 0; i < study.series.length; i++) {
      const s = study.series[i];
      const parts = [`Series ${i + 1}`];
      if (s.modality) parts.push(s.modality);
      parts.push(`${s.instanceCount} images`);
      if (s.equipment?.manufacturer) parts.push(s.equipment.manufacturer);
      if (s.equipment?.manufacturerModelName) parts.push(s.equipment.manufacturerModelName);
      doc.text(parts.join("  |  "), margin, y);
      y += 4.5;
    }
    y += 4;
  }

  // Viewport screenshot
  if (canvas) {
    const imgData = canvas.toDataURL("image/png");
    const imgProps = doc.getImageProperties(imgData);
    const imgRatio = imgProps.width / imgProps.height;
    const maxImgW = contentW;
    const maxImgH = 130;
    let imgW = maxImgW;
    let imgH = imgW / imgRatio;
    if (imgH > maxImgH) {
      imgH = maxImgH;
      imgW = imgH * imgRatio;
    }
    const imgX = margin + (contentW - imgW) / 2;

    // Check if we need a new page
    if (y + imgH + 30 > 297) {
      doc.addPage();
      y = margin;
    }

    doc.setDrawColor(52, 211, 153, 0.2);
    doc.setLineWidth(0.5);

    // Add "Key Image" label
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(52, 211, 153);
    doc.text("Key Image", margin, y);
    y += 5;

    doc.addImage(imgData, "PNG", imgX, y, imgW, imgH, undefined, "FAST");
    y += imgH + 6;

    // Caption
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(`Slice view — Study UID: ${study.studyUid.slice(0, 20)}...`, margin, y);
  }

  // Footer
  const footerY = 280;
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by CoreVita", margin, footerY);

  if (plan === "starter") {
    doc.setFontSize(8);
    doc.setTextColor(245, 158, 11, 0.5);
    doc.text("CoreVita Free Plan — corevita.app", pageW / 2, footerY, { align: "center" });
  } else {
    doc.setTextColor(52, 211, 153, 0.4);
    doc.text("corevita.app", pageW - margin, footerY, { align: "right" });
  }

  return doc;
}
